In [78]:
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt;
import seaborn as sns;

In [79]:
df = pd.read_excel("Updates_transaction.xlsx")

In [80]:
print("\n--No of missing Customers--");
print(df['CustomerID'].isna().sum());

--No of missing Customers--
135080

In [81]:
df_clean = df.dropna(subset=['CustomerID']);
print(f"\n Shape of dataset After removing missing CustomerId's {df_clean.shape}");

 Shape of dataset After removing missing CustomerId's (406829, 9)

In [82]:
print("\n --Duplicates--");
print(df_clean.duplicated().sum());

 --Duplicates--
5225

In [83]:
print("\n Dropping all the duplicates");
duplicate_df = df_clean[df_clean.duplicated(keep=False)];
df_clean=df_clean.drop_duplicates();
print(df_clean.duplicated().sum());

 Dropping all the duplicates
0

In [84]:
df_clean.shape

(401604, 9)

In [85]:
print("\n--Negative price values and quantities--");
print(df_clean[df_clean['Quantity']<0]['Quantity'].count());
print(df_clean[df_clean['TransactionValue']<0]['TransactionValue'].count());

--Negative price values and quantities--
8872
8872

In [86]:
cancellations_df= df_clean[df_clean['InvoiceNo'].str.startswith('C',na=False)].copy()
cancellations_df.shape

(8872, 9)

In [87]:
cancellations_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TransactionValue
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom,-27.50
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom,-4.65
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom,-19.80
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,-6.96
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,-6.96
...,...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom,-9.13
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom,-224.69
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom,-54.75
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom,-1.25
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom,-6.25

In [88]:
df_clean = df_clean[~df_clean['InvoiceNo'].astype(str).str.startswith('C')]

In [89]:
df_clean.shape

(392732, 9)

In [90]:
print(df_clean[df_clean['Quantity']<0]['Quantity'].count());
print(df_clean[df_clean['TransactionValue']<0]['TransactionValue'].count());

0
0

In [91]:
print("\n --Removing items with 0 as transaction--");
df_clean=df_clean[(df_clean['Quantity']>0) & (df_clean['UnitPrice']>0)]
print(df_clean.shape);
df_clean

 --Removing items with 0 as transaction--
(392692, 9)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TransactionValue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

In [93]:
print("\n --Standardize Description--");
df_clean['Description']=df_clean['Description'].str.strip().str.upper();
df_clean['Description']

 --Standardize Description--

0          WHITE HANGING HEART T-LIGHT HOLDER
1                         WHITE METAL LANTERN
2              CREAM CUPID HEARTS COAT HANGER
3         KNITTED UNION FLAG HOT WATER BOTTLE
4              RED WOOLLY HOTTIE WHITE HEART.
                         ...
541904            PACK OF 20 SPACEBOY NAPKINS
541905            CHILDREN'S APRON DOLLY GIRL
541906           CHILDRENS CUTLERY DOLLY GIRL
541907        CHILDRENS CUTLERY CIRCUS PARADE
541908           BAKING SET 9 PIECE RETROSPOT
Name: Description, Length: 392692, dtype: object

In [96]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 392692 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   InvoiceNo         392692 non-null  object
 1   StockCode         392692 non-null  object
 2   Description       392692 non-null  object
 3   Quantity          392692 non-null  int64
 4   InvoiceDate       392692 non-null  datetime64[us]
 5   UnitPrice         392692 non-null  float64
 6   CustomerID        392692 non-null  float64
 7   Country           392692 non-null  str
 8   TransactionValue  392692 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), object(3), str(1)
memory usage: 30.0+ MB

In [97]:
print("\n --Date Range --");
print((df_clean['InvoiceDate'].max()-df_clean['InvoiceDate'].min()).days);

 --Date Range --
373